### ISSUE TITLE
Inference from TypeScript objects

### ISSUE THREAD

**Issue by cpjolicoeur** [mojotech/json-type-validation#12]
Would it be possible to have this library accept a TypeScript `interface` as a parameter and infer the `Decoder` shape from it?

There seems to be quite a lot of duplication involved in declaring a TS interface and then declaring (in most cases) the same exact shape for the `Decoder` of that object.  Could this library provide a function that would accept the TS interface object as an argument and return a fully formed decoder from it?

I haven't look at TS internals enough yet to know, but I'm assuming we may be able to do this?

**Comment by mulias** [comment]
As for as I know the answer to this is a hard no. There is no such thing as an "inference object" since everything related to type checking is stripped out during the compilation step. There are forks of TypeScript that provide type reflection at runtime, but the TS team has made it clear that such functionality is not part of the core language's vision. This is stated by [non-goal #5](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals):

> [Do not] Add or rely on run-time type information in programs, or emit different code based on the results of the type system. Instead, encourage programming patterns that do not require run-time metadata.

At one point I looked into auto-generating decoders for enums because those can have an object representation at runtime. But this leads to issues in recent versions of TS -- if the `enum` is a `const enum` then TS hard-codes the enum values into the code, similar to a C macro. The enum object isn't included in the compiled js.

There are a number of similar transformations that could be provided for utility, but none of them are as convenient as `interface -> Decoder`. We could:
* take a TS `interface` declaration as a string, and produce the corresponding `Decoder`
* take a valid JSON object and return a `Decoder` that validates the object
* take a spec written in Swagger, RAML, or JSON Schema and produce `Decoders` (this is what the Amica team really wants for RAML, but it's a significant amount of work)

**Comment by mulias** [comment]
To put this another way, a type can only be used for type annotations, it is not a valid value/argument. This issue comes up other places in the library, like decoders for type literals -- I would like it if `constant<true>(true)` and `constant(true)` meant the same thing to the typechecker, but there's no way to use the function argument as the type argument too.

**Comment by mulias** [comment]
> I would like it if `constant<'xyz'>('xyz')` and `constant('xyz')` meant the same thing to the typechecker, but there's no way to use the function argument as the type argument too.

Funny enough this specific example has been fixed, but the point in general still stands.
